version: "2"
# plugins:
#   duplication:
#     enabled: false
#     exclude_patterns:
#       - "public/"
#   structure:
#     enabled: false
#   reek:
#     enabled: true
#     channel: "beta"
#   reek-test:
#     enabled: false

  checks:
    argument-count:
      enabled: true
    complex-logic:
      enabled: true
    file-lines:
      enabled: true
    method-complexity:
      enabled: true
    method-count:
      enabled: false # rubocop checks this
    method-lines:
      enabled: false # rubocop checks this
    nested-control-flow:
      enabled: true
    return-statements:
      enabled: true
    similar-code:
      enabled: true
    identical-code:
      enabled: true
  
  plugins:
    brakeman:
      enabled: false
    bundler-audit:
      enabled: false
    flog:
      enabled: true
      exclude_patterns:
        - 'spec/'
    reek:
      enabled: true
      channel: beta
      exclude_patterns:
        - 'spec/'
    # rubocop:
    #   enabled: true
    #   channel: rubocop-0-89
    #   config:
    #     file: .rubocop.codeclimate.yml
    duplication:
      enabled: true
      exclude_patterns:
        - 'spec/**/*.rb'
  
  exclude_patterns:
    - 'config/'
    - 'db/'
    - 'app/assets/plugins/'
    - 'app/assets/reader/'
    - 'app/assets/images/'
    - 'features/'
    - 'frontend/'
    - 'public/'
    - '**/node_modules/'
    - 'script/'
    - '**/test/'
    - '**/tests/'
    - '**/vendor/'
  